version: "3.8"

services:
  # 1. Base de Datos del Negocio (MySQL 8)
  # Aquí se guardarán los usuarios y contratos
  mysqldb:
    image: mysql:8.0
    container_name: uce_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: becas_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - uce-net
    command: --default-authentication-plugin=mysql_native_password

  # 2. Caché y Seguridad (Redis)
  # Aquí guardaremos los Refresh Tokens (JWT)
  redisdb:
    image: redis:alpine
    container_name: uce_redis
    ports:
      - "6379:6379"
    networks:
      - uce-net

networks:
  uce-net:
    driver: bridge

volumes:
  mysql_data:
